title = "M.A. Niemiro"
baseURL = ""
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = false
math = true          # enable KaTeX (https://katex.org/) globally

[params]
  author = "Matthew A. Niemiro"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    url = "/notes"
    weight = 2
	[[menu.main]]
    name = "Miscellany"
    url = "/misc"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
